#ifndef PREFETCH_KCACHE_IOCTL_H
#define PREFETCH_KCACHE_IOCTL_H

#include <linux/ioctl.h>
#include <linux/types.h>

#define PREFETCH_KCACHE_IOC_MAGIC 'p'

#define PREFETCH_KCACHE_IOC_GET_ADDR _IOR(PREFETCH_KCACHE_IOC_MAGIC, 1, __u64)
#define PREFETCH_KCACHE_IOC_FLUSH    _IO(PREFETCH_KCACHE_IOC_MAGIC, 2)
#define PREFETCH_KCACHE_IOC_MEASURE  _IOR(PREFETCH_KCACHE_IOC_MAGIC, 3, __u64)
#define PREFETCH_KCACHE_IOC_PREFETCH _IO(PREFETCH_KCACHE_IOC_MAGIC, 4)

#endif
